apiVersion: v1
kind: ConfigMap
metadata:
  name: solidarytech-config
data:
  AWS_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE: "SolidaryTechVolunteers"
  NGO_PORT: "8081"
  DONATION_PORT: "8082"
  VOLUNTEER_PORT: "8083"

---
apiVersion: v1
kind: Secret
metadata:
  name: solidarytech-secrets
type: Opaque
stringData:
  # ATENÇÃO: Num ambiente real (DevSecOps), não colocamos secrets aqui (usa-se o AWS Secrets Manager ou Vault).
  # Colocamos apenas como placeholder para o manifesto ser validado.
  NGO_DATABASE_URL: "postgres://postgres:senha@postgres-host/ngo_db"
  DONATION_DATABASE_URL: "postgres://postgres:senha@postgres-host/donation_db"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/123/solidary-donations"
